spring:
  application:
    name: spring-backend
  jpa:
    database: sql_server
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:sqlserver://localhost:5434
    username: SA
    password: Pass@word
